spring:
  application:
    name: mail-service
  config:
    import: optional:configserver:http://localhost:8088

  mail:
    host: localhost
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          ssl:
            enable: false    
server:
  port: 8087
