spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8088

logging:
  file:
    name: C:\Vijay\logs\ELK-logstack\TrendFusion\logs-product.log
     