server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    import: optional:configserver:http://localhost:8088
  mail:
    host: smtp.gmail.com
    port: 587
    username: vijayjadhav888@gmail.com
    password: Vijay@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com        
      
logging:
  file:
    name: C:\Vijay\logs\ELK-logstack\TrendFusion\logs-mail.log
    

msg: "message from GIT repo of mail service"

