spring:
  cloud:
    config:
      server:
        git:
           uri: https://github.com/vijayjadhav888/applications
           searchPaths: app-config/TrendFusion
           cloneOnStart: true
           
server:
  port: 8088