spring:
  cloud:
    config:
      server:
        git:
           uri: https://github.com/vijayjadhav888/trendfusion
           searchPaths: '{order-service}'
           cloneOnStart: true
           

