
spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8088
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerdb
      
      
logging:
  file:
    name: C:\Vijay\logs\ELK-logstack\TrendFusion\logs-customer.log
    